// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TitanHelp.EntityFramework.Data;

#nullable disable

namespace TitanHelp.EntityFramework.Migrations
{
    [DbContext(typeof(TicketContext))]
    [Migration("20221006154900_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");
#pragma warning restore 612, 618
        }
    }
}
